sudo: required

language: python

services:
    - docker

install:
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always
